In [23]:
import pandas as pd 
import sqlite3
  
con = sqlite3.connect(r'C:\Users\MUEENUDHEEN\ipl_cricket-analatycs\ipl-cricket-analytics\data\raw\ipl.db') 
  
def q(sql): 
    """Run a SELECT and show the result as a table.""" 
    return pd.read_sql(sql, con)


def run_sql_file(path): 
    """Read a .sql file and execute every statement in it.""" 
    with open(path, 'r') as f: 
        script = f.read() 
    con.executescript(script) 
    con.commit() 
    print('ran', path)

In [24]:
run_sql_file(r"C:\Users\MUEENUDHEEN\ipl_cricket-analatycs\ipl-cricket-analytics\sql\09_analysis_views.sql")

ran C:\Users\MUEENUDHEEN\ipl_cricket-analatycs\ipl-cricket-analytics\sql\09_analysis_views.sql

In [25]:
q("select * from v_ball limit 10;")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0

In [26]:
q("SELECT * FROM v_innings LIMIT 10;")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
5,335984,2,Delhi Capitals,Rajasthan Royals,132,1,91
6,335985,1,Mumbai Indians,Royal Challengers Bangalore,165,7,120
7,335985,2,Royal Challengers Bangalore,Mumbai Indians,166,5,118
8,335986,1,Sunrisers Hyderabad,Kolkata Knight Riders,110,10,112
9,335986,2,Kolkata Knight Riders,Sunrisers Hyderabad,112,5,114

In [28]:
q("SELECT * FROM v_match_totals LIMIT 10;")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id,season_year,first_innings_runs,bat_first_team,chase_won
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,BB McCullum,1,6,1,6,46.0,2008,222,Kolkata Knight Riders,0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Yuvraj Singh,2,1,1,2,15.0,2017,207,Sunrisers Hyderabad,0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,SPD Smith,4,3,4,4,36.0,2017,184,Mumbai Indians,1
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,CA Lynn,5,6,6,6,57.0,2017,183,Gujarat Lions,1
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,GJ Maxwell,494,4,494,494,71.0,2017,163,Rising Pune Supergiant,1
5,1082595,2017,6,Bengaluru,2017-04-08,Indian Premier League,5.0,male,T20,T20,...,KM Jadhav,1,252,1,1,4.0,2017,157,Royal Challengers Bangalore,0
6,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,Rashid Khan,2,5,2,2,22.0,2017,135,Gujarat Lions,1
7,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,N Rana,3,6,3,3,26.0,2017,178,Kolkata Knight Riders,1
8,1082598,2017,6,Indore,2017-04-10,Indian Premier League,8.0,male,T20,T20,...,AR Patel,494,1,1,494,70.0,2017,148,Royal Challengers Bangalore,1
9,1082599,2017,6,Pune,2017-04-11,Indian Premier League,9.0,male,T20,T20,...,SV Samson,4,252,4,252,180.0,2017,205,Delhi Capitals,0

In [29]:
import sqlite3
import pandas as pd

# Connect to IPL database
conn = sqlite3.connect("../data/raw/ipl.db")

print("Database connected successfully!")

Database connected successfully!

In [30]:
query = """
SELECT name
FROM sqlite_master
WHERE type IN ('table', 'view')
ORDER BY name;
"""

pd.read_sql_query(query, conn)

                      name
0               deliveries
1                  matches
2            matches_clean
3                  players
4                    teams
5                   v_ball
6       v_deliveries_clean
7                v_example
8                v_innings
9           v_match_totals
10    v_matches_city_clean
11         v_matches_clean
12  v_matches_season_clean
13           v_teams_clean
14                  venues

In [31]:
query = """
SELECT *
FROM v_ball
LIMIT 10;
"""

df = pd.read_sql_query(query, conn)
df

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,4,0

In [32]:
query = """
SELECT *
FROM v_innings
LIMIT 10;
"""

df = pd.read_sql_query(query, conn)
df

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
5,335984,2,Delhi Capitals,Rajasthan Royals,132,1,91
6,335985,1,Mumbai Indians,Royal Challengers Bangalore,165,7,120
7,335985,2,Royal Challengers Bangalore,Mumbai Indians,166,5,118
8,335986,1,Sunrisers Hyderabad,Kolkata Knight Riders,110,10,112
9,335986,2,Kolkata Knight Riders,Sunrisers Hyderabad,112,5,114

In [33]:
query = """
SELECT
    match_id,
    innings,
    batting_team,
    runs
FROM v_innings
ORDER BY runs DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, conn)
df

   match_id  innings                 batting_team  runs
0   1426268        1          Sunrisers Hyderabad   287
1   1473439        1          Sunrisers Hyderabad   286
2   1473505        1          Sunrisers Hyderabad   278
3   1422126        1          Sunrisers Hyderabad   277
4   1422134        1        Kolkata Knight Riders   272
5   1426273        1          Sunrisers Hyderabad   266
6   1529278        2                 Punjab Kings   265
7   1529278        1               Delhi Capitals   264
8    598027        1  Royal Challengers Bangalore   263
9   1426268        2  Royal Challengers Bangalore   262

In [34]:
query = """
SELECT
    batting_team,
    ROUND(AVG(runs), 2) AS average_score
FROM v_innings
GROUP BY batting_team
ORDER BY average_score DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   batting_team  average_score
0                Gujarat Titans         176.75
1          Lucknow Super Giants         174.38
2           Chennai Super Kings         164.31
3                  Punjab Kings         163.66
4                Mumbai Indians         163.22
5                 Gujarat Lions         161.87
6           Sunrisers Hyderabad         161.10
7   Royal Challengers Bangalore         160.90
8              Rajasthan Royals         160.49
9                Delhi Capitals         157.44
10        Kolkata Knight Riders         156.40
11       Rising Pune Supergiant         151.10
12                Pune Warriors         141.29
13         Kochi Tuskers Kerala         135.79

In [35]:
query = """
SELECT
    batting_team,
    SUM(runs) AS total_runs
FROM v_innings
GROUP BY batting_team
ORDER BY total_runs DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   batting_team  total_runs
0                Mumbai Indians       46517
1           Sunrisers Hyderabad       44948
2   Royal Challengers Bangalore       44890
3                  Punjab Kings       44352
4                Delhi Capitals       43297
5           Chennai Super Kings       42557
6         Kolkata Knight Riders       42540
7              Rajasthan Royals       39159
8                Gujarat Titans       12196
9          Lucknow Super Giants       11509
10                Pune Warriors        6358
11                Gujarat Lions        4856
12       Rising Pune Supergiant        4533
13         Kochi Tuskers Kerala        1901

In [36]:
query = """
SELECT
    batting_team,
    ROUND(AVG(runs), 2) AS average_score
FROM v_innings
GROUP BY batting_team
ORDER BY average_score DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   batting_team  average_score
0                Gujarat Titans         176.75
1          Lucknow Super Giants         174.38
2           Chennai Super Kings         164.31
3                  Punjab Kings         163.66
4                Mumbai Indians         163.22
5                 Gujarat Lions         161.87
6           Sunrisers Hyderabad         161.10
7   Royal Challengers Bangalore         160.90
8              Rajasthan Royals         160.49
9                Delhi Capitals         157.44
10        Kolkata Knight Riders         156.40
11       Rising Pune Supergiant         151.10
12                Pune Warriors         141.29
13         Kochi Tuskers Kerala         135.79

In [37]:
query = """
SELECT
    batting_team,
    ROUND(AVG(runs), 2) AS average_score
FROM v_innings
GROUP BY batting_team
HAVING AVG(runs) > 160
ORDER BY average_score DESC;
"""

df = pd.read_sql_query(query, conn)
df

                  batting_team  average_score
0               Gujarat Titans         176.75
1         Lucknow Super Giants         174.38
2          Chennai Super Kings         164.31
3                 Punjab Kings         163.66
4               Mumbai Indians         163.22
5                Gujarat Lions         161.87
6          Sunrisers Hyderabad         161.10
7  Royal Challengers Bangalore         160.90
8             Rajasthan Royals         160.49

In [38]:
query = """
SELECT
    batting_team,
    MAX(runs) AS highest_score
FROM v_innings
GROUP BY batting_team
ORDER BY highest_score DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   batting_team  highest_score
0           Sunrisers Hyderabad            287
1         Kolkata Knight Riders            272
2                  Punjab Kings            265
3                Delhi Capitals            264
4   Royal Challengers Bangalore            263
5          Lucknow Super Giants            257
6                Mumbai Indians            247
7           Chennai Super Kings            246
8              Rajasthan Royals            242
9                Gujarat Titans            233
10                Gujarat Lions            208
11       Rising Pune Supergiant            195
12                Pune Warriors            192
13         Kochi Tuskers Kerala            184

In [39]:
query = """
SELECT
    batting_team,
    COUNT(*) AS innings_count
FROM v_innings
GROUP BY batting_team
ORDER BY innings_count DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   batting_team  innings_count
0                Mumbai Indians            285
1           Sunrisers Hyderabad            279
2   Royal Challengers Bangalore            279
3                Delhi Capitals            275
4         Kolkata Knight Riders            272
5                  Punjab Kings            271
6           Chennai Super Kings            259
7              Rajasthan Royals            244
8                Gujarat Titans             69
9          Lucknow Super Giants             66
10                Pune Warriors             45
11       Rising Pune Supergiant             30
12                Gujarat Lions             30
13         Kochi Tuskers Kerala             14

In [40]:
query = """
SELECT
    match_id,
    first_innings_runs,
    bat_first_team,
    match_winner
FROM v_match_totals
WHERE first_innings_runs > 200
ORDER BY first_innings_runs DESC;
"""

df = pd.read_sql_query(query, conn)
df

,match_id,first_innings_runs,bat_first_team,match_winner
0,1426268,287,Sunrisers Hyderabad,Sunrisers Hyderabad
1,1473439,286,Sunrisers Hyderabad,Sunrisers Hyderabad
2,1473505,278,Sunrisers Hyderabad,Sunrisers Hyderabad
3,1422126,277,Sunrisers Hyderabad,Sunrisers Hyderabad
4,1422134,272,Kolkata Knight Riders,Kolkata Knight Riders
...,...,...,...,...
184,1426288,201,Sunrisers Hyderabad,Sunrisers Hyderabad
185,734011,201,Rajasthan Royals,Rajasthan Royals
186,829787,201,Sunrisers Hyderabad,Sunrisers Hyderabad
187,1527674,201,Sunrisers Hyderabad,Royal Challengers Bangalore
188,1527689,201,Royal Challengers Bangalore,Rajasthan Royals

In [41]:
query = """
SELECT
    MAX(first_innings_runs) AS highest_first_innings_score
FROM v_match_totals;
"""

df = pd.read_sql_query(query, conn)
df

   highest_first_innings_score
0                          287

In [42]:
query = """
SELECT
    match_winner,
    COUNT(*) AS wins
FROM v_match_totals
GROUP BY match_winner
ORDER BY wins DESC;
"""

df = pd.read_sql_query(query, conn)
df

                   match_winner  wins
0                Mumbai Indians   153
1           Chennai Super Kings   145
2   Royal Challengers Bangalore   138
3         Kolkata Knight Riders   136
4           Sunrisers Hyderabad   128
5                  Punjab Kings   125
6                Delhi Capitals   122
7              Rajasthan Royals   120
8                Gujarat Titans    42
9          Lucknow Super Giants    32
10       Rising Pune Supergiant    15
11                Gujarat Lions    13
12                Pune Warriors    12
13         Kochi Tuskers Kerala     6

In [43]:
query = """
SELECT
    ROUND(
        100.0 * AVG(chase_won),
        2
    ) AS chase_win_percentage
FROM v_match_totals;
"""

df = pd.read_sql_query(query, conn)
df

   chase_win_percentage
0                 54.51

In [50]:
query = """
SELECT
    venue_clean,
    COUNT(*) AS matches,
    ROUND(
        100.0 * AVG(chase_won),
        2
    ) AS chase_win_percentage
FROM v_match_totals
GROUP BY venue_clean
HAVING COUNT(*) >= 30
ORDER BY chase_win_percentage DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, conn)
df

DatabaseError: Execution failed on sql '
SELECT
    venue_clean,
    COUNT(*) AS matches,
    ROUND(
        100.0 * AVG(chase_won),
        2
    ) AS chase_win_percentage
FROM v_match_totals
GROUP BY venue_clean
HAVING COUNT(*) >= 30
ORDER BY chase_win_percentage DESC
LIMIT 10;
': no such column: venue_clean

In [51]:
query = """
PRAGMA table_info(v_match_totals);
"""

df = pd.read_sql_query(query, conn)
df

    cid                name  type  notnull dflt_value  pk
0     0            match_id   INT        0       None   0
1     1           season_id   INT        0       None   0
2     2      balls_per_over   INT        0       None   0
3     3                city  TEXT        0       None   0
4     4          match_date  TEXT        0       None   0
5     5          event_name  TEXT        0       None   0
6     6        match_number  REAL        0       None   0
7     7              gender  TEXT        0       None   0
8     8          match_type  TEXT        0       None   0
9     9              format  TEXT        0       None   0
10   10               overs   INT        0       None   0
11   11              season  TEXT        0       None   0
12   12           team_type  TEXT        0       None   0
13   13               venue  TEXT        0       None   0
14   14         toss_winner  TEXT        0       None   0
15   15               team1  TEXT        0       None   0
16   16               team2  TEXT        0       None   0
17   17       toss_decision  TEXT        0       None   0
18   18        match_winner  TEXT        0       None   0
19   19         win_by_runs  REAL        0       None   0
20   20      win_by_wickets  REAL        0       None   0
21   21              result  TEXT        0       None   0
22   22     player_of_match  TEXT        0       None   0
23   23            team1_id   INT        0       None   0
24   24            team2_id   INT        0       None   0
25   25      toss_winner_id   INT        0       None   0
26   26     match_winner_id   INT        0       None   0
27   27  player_of_match_id  REAL        0       None   0
28   28         season_year   INT        0       None   0
29   29  first_innings_runs              0       None   0
30   30      bat_first_team              0       None   0
31   31           chase_won              0       None   0

In [52]:
query = """
SELECT
    phase,
    SUM(total_runs) AS total_runs
FROM v_ball
GROUP BY phase
ORDER BY total_runs DESC;
"""

df = pd.read_sql_query(query, conn)
df

       phase  total_runs
0     Middle      169160
1  Powerplay      116397
2      Death      104056

In [53]:
conn.close()

print("Database connection closed.")

Database connection closed.